### PR TITLE
feat(ReactHooks): introduce hooks useUIRouter, useUISref and useUISrefActive

### PR DESCRIPTION
**Pull request by Anber**
This PR adds 3 useful hooks: useUIRouter, useUISref, and useUISrefActive.
There are no breaking changes except the new version of React.

```jsx
const Link = ({ to, children, className, ...otherProps }) => {
  const linkProps = useUISref(to);
  const isActive = useUISrefActive(to);
  const props = {
    ...otherProps,
    ...linkProps,
    className: classNames(className, { active: isActive }),
  };

  return <a {...props}>{children}</a>;
});
```

### CODE REVIEW

**Comment by Anber** [comment]
I've just found `hookz` branch… It looks like we are trying to solve two different problems. I can try to merge with `hookz`. @christopherthielen @elboman what do you think?

**Comment by christopherthielen** [comment]
I'll let @elboman respond because he's done all the work on the `hookz` branch

**Comment by Anber** [comment]
I've merged two hooks branches and made a PR in ui-router/react-hybrid

**Comment by Anber** [comment]
It looks like `sample-app-react` should also be fixed…
@elboman maybe we can just export UIRouterCosumer/UIRouterProvider for backward compatibility?

**Comment by elboman** [comment]
Hey @Anber, sorry I didn't see this earlier, I've been swamped lately!
I also have the `ReactRouter` implementation updated to hooks locally, just need to clean it and it should be ready.

I wanted to create hooks to consume some of the router functionalities for users, but I approached changing the internals first to understand what could be used in common.

I'll take a look at your updated PR and ping you back!

**Comment by Anber** [comment]
Hi @elboman, let me know if I can help you!

**Comment by pahen** [comment]
What's the status of this? It would be awesome if the context was exported at least so we can start using `React.useContext`

**Comment by christopherthielen** [comment]
@anber @elboman @pahen  I merged these changes in https://github.com/ui-router/react/pull/574 and would appreciate any feedback

**Comment by pahen** [comment]
Sweet! 🥇https://github.com/ui-router/react/blob/master/src/hooks/useRouter.ts is exactly what I was missing since I do `router.stateService.go('myState')` a lot. Would it be possible to have a dedicated hook for that maybe?

**Comment by christopherthielen** [comment]
how about just destructuring the `stateService` from the router?
```
const { stateService } = useRouter();
```

https://github.com/ui-router/sample-app-react/blob/hooks/src/main/App.js#L14-L18

**Comment by pahen** [comment]
Yes, that’s easy enough 👍 Great work with the hooks API 💥

**Pull request closed without merging**
