### PR TITLE
Fix issues when using React.StrictMode

### PR DESCRIPTION
**Pull request by wallzero**
In anticipation for React suspense and concurrent mode, it is advisable to test with `<React.StrictMode>` and resolve any issues.

- Wrap example in `<React.StrictMode>`
- Switch `componentWillMount` to `componentDidMount`
- Switch `UIRouter` component constructor to `componentDidMount`
- fix minor build and test issues

### CODE REVIEW

**Comment by wallzero** [comment]
Resolves #463

**Comment by christopherthielen** [comment]
@wallzero can you rebase this against the latest master?  I updated a few dependencies

**Comment by wallzero** [comment]
Okay it should be synced with master now.

**Comment by christopherthielen** [comment]
hmm, github is telling me that it can't be rebased due to conflicts 🤔 

Worst case, we can always make a new branch/PR and cherry pick your commits

**Comment by wallzero** [comment]
Okay I'll do that

**Pull request closed without merging**
