### PR TITLE
refactor(*): switch to `prop-types` package

### PR DESCRIPTION
**Pull request by Kukkimonsuta**
This introduces new dependency on `prop-types` package as recommended in latest react:

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

### CODE REVIEW

**Comment by elboman** [comment]
Great, looks fine, but we need to test is everything is working when using this package with rollup as bundler, since I know it might complain and break over `import * as something` syntax.

**Comment by Kukkimonsuta** [comment]
I've tried to setup a rollup sample, but failed miserably, however I'm pretty sure this will be fine as it's used in non-hacky way, same as `import * as React from 'react';`. The rollup issue seems to occur when doing something like:

```ts
import * as something from 'something';
something();
```

**Comment by elboman** [comment]
We are not using it in a hacky way, but the package is not written in order to function properly with rollup, if I'm not mistaken. I tried to set up a simple test app with roll up with these changes in the `ui-router-react`. The module gets imported but not as expected and throws.

This is how it gets transpiled:
```jsx
var PropTypes$2 = Object.freeze({
	default: index$3,
	__moduleExports: index$3
});
```
So the actual package goes under the `default` prop. I'm not sure how to fix this without some ugly hack like checking for the `default` prop on the module or something.

Suggestions?

**Comment by Kukkimonsuta** [comment]
Could you share your rollup test app? For the love of god I can't get it to work at all.

I feel like introducing babel into the build pipeline is overkill and would prefer just using `const PropTypes = require('prop-types');` which should avoid these problems, but we will loose typings.

**Comment by Kukkimonsuta** [comment]
I've tried applying the same magic solution as used in `classnames`, could you please test whether it made any difference?

**Comment by elboman** [comment]
Unfortunately no luck, finally had some chance to test out the changes with the magic rollup solution, but it's not working.

I used this repo to do the testing: https://github.com/elboman/ui-router-react-rollup-test
You need to compile ui-router-react locally and `npm link`/`yarn link` the package, or just copy/paste the `lib`/`lib-esm` for a quick test.

The behaviour is the same: in Rollup the module gets imported and wrapped with a `default` property which renders it unusable unless we start checking for it.

**Comment by Kukkimonsuta** [comment]
In that case I don't know how to solve this and not hate myself. I'll try to raise an issue on rollup and see if there is any way they could help.

**Comment by Kukkimonsuta** [comment]
I've found that if I explicitly name the exports in `rollup.config.js` in the `commonjs` plugins `namedExports`:

```
'prop-types': [
          'any',
          'array',
          'arrayOf',
          'bool',
          'checkPropTypes',
          'element',
          'func',
          'instanceOf',
          'node',
          'number',
          'object',
          'objectOf',
          'oneOf',
          'oneOfType',
          'shape',
          'string',
          'symbol'
        ]
```

it gets emitted like this:

```
var index_1 = index.any;
var index_2 = index.array;
var index_3 = index.arrayOf;
var index_4 = index.bool;
var index_5 = index.checkPropTypes;
var index_6 = index.element;
var index_7 = index.func;
var index_8 = index.instanceOf;
var index_9 = index.node;
var index_10 = index.number;
var index_11 = index.object;
var index_12 = index.objectOf;
var index_13 = index.oneOf;
var index_14 = index.oneOfType;
var index_15 = index.shape;
var index_16 = index.string;
var index_17 = index.symbol;


var PropTypes = Object.freeze({
	default: index,
	__moduleExports: index,
	any: index_1,
	array: index_2,
	arrayOf: index_3,
	bool: index_4,
	checkPropTypes: index_5,
	element: index_6,
	func: index_7,
	instanceOf: index_8,
	node: index_9,
	number: index_10,
	object: index_11,
	objectOf: index_12,
	oneOf: index_13,
	oneOfType: index_14,
	shape: index_15,
	string: index_16,
	symbol: index_17
});
```
and seems to contain the right things.

It is not something we can handle in the library, but users may use it to make it work I suppose.

Anyway, I'm sorry, but I'm not putting any more time into this, rollup doesn't seem worth it until everything is built using es6 modules since specifying all named exports in config is just insanity.

**Comment by elboman** [comment]
Well, that's great. The problem obviously comes from the fact that `prop-types` doesn't use ES6 modules, and I think it's fair that the config should be related to rollup on the user side. Fine by me.

If you revert back to the previous commit (without the magic stuff) I'll merge it to master so we can finally release 0.5.0 and people can start using it.

**Comment by Kukkimonsuta** [comment]
Done, but just to be sure please test it too :)

Is it planned to also switch to `@uirouter/core` v5.0.0 within this release?

**Comment by elboman** [comment]
Yeah I tested it with the repo I linked you and it works fine with the changes to the rollup config you mentioned.

I think switching to core@5.0.0 should be fine, I just need to check the breaking changes for users when they update

**Pull request merged**
