### PR TITLE
feat(UISrefActive): nested UISrefActive

### PR DESCRIPTION
**Pull request by Anber**

### CODE REVIEW

**Comment by christopherthielen** [comment]
@elboman what say you?

**Comment by Anber** [comment]
Maybe there is a simpler way to mark ancestors as active?

btw, I've squashed commits.

**Comment by elboman** [comment]
sorry, I've taken a look the other day but forgot to answer. Looks good to me, I haven't tested it tho. I'll be on it later/tomorrow ;)

**Comment by elboman** [comment]
great, thanks!

**Pull request merged**
